tableDbConfig:
  - tableConfigId: "get_smms_assets_list_ser_count"
    tableName: "smms_assets"
    orderBy: "count desc"
    defaultFilterMapping:
      "all_division": ["South Eastern Railway"]
    filterParameter:
      - "zone"
      - "division"
      - "file_date"
    groupBy:
      - "zone"
      - "division"
      - "sub_section"
      - "section_officer"
      - "section"
      - "location"
    selectColumnName:
      - "zone"
      - "division"
      - "sub_section"
      - "section_officer"
      - "section"
      - "location"
      - "COUNT(*) as count"
    columnName:
      - "zone"
      - "division"
      - "sub_section"
      - "section_officer"
      - "section"
      - "location"
      - "count"
  - tableConfigId: "get_smms_assets_list"
    tableName: "smms_assets"
    allowEmptyFilter: false
    filterParameter:
      - "zone"
      - "division"
      - "file_date"
    selectColumnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "asset_code_v2 as asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "DATE(added_time) as added_date"
      - "added_time"
      - "updated_time"
      - "DATE_FORMAT(added_time, '%Y-%m-%d-%H') as added_date_hour"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "added_time"
      - "updated_time"
      - "added_date"
      - "added_date_hour"
