tableDbConfig:
  - tableConfigId: "get-requisition-status"
    tableName: "requisition_status"
    orderBy: "id desc"
    defaultFilterMapping:
      "on_roll": ["s&t|signal|telecom|safety|ministrial"]
      "all": [""]
    filterParameter:
      - "row_unique_number"
    selectColumnName:
      - "req_date"
      - "dp_date"
      - "remark_date"
      - "material_status"
      - "file_date"
      - "department"
      - "s_no"
      - "items"
      - "unit"
      - "qty"
      - "demand_no"
      - "demand_date"
      - "budget"
      - "req_rate"
      - "req_amount"
      - "allocation"
      - "project_id"
      - "work_id"
      - "estimate_no"
      - "estimate_item_no"
      - "po_number"
      - "dp"
      - "po_rate"
      - "po_amount"
      - "material_received_remark"
      - "bill_paid"
      - "co7_number"
      - "req_remark"
      - "row_unique_number"
      - "project_id_item_no"
      - "estimate_ref_count"
      - "estimate_remark"
      - "indent_status"
      - "category"
      - "sub_category"
      - "make"
      - "DATE(added_time) as added_date"
    columnName:
      - "req_date"
      - "dp_date"
      - "remark_date"
      - "material_status"
      - "file_date"
      - "department"
      - "s_no"
      - "items"
      - "unit"
      - "qty"
      - "demand_no"
      - "demand_date"
      - "budget"
      - "req_rate"
      - "req_amount"
      - "allocation"
      - "project_id"
      - "work_id"
      - "estimate_no"
      - "estimate_item_no"
      - "po_number"
      - "dp"
      - "po_rate"
      - "po_amount"
      - "material_received_remark"
      - "bill_paid"
      - "co7_number"
      - "req_remark"
      - "row_unique_number"
      - "project_id_item_no"
      - "estimate_ref_count"
      - "estimate_remark"
      - "indent_status"
      - "category"
      - "sub_category"
      - "make"
      - "added_date"
  - tableConfigId: "csv-mysql-update-requisition-status"
    tableName: "requisition_status"
    orderBy: "id desc"
    excelConfigId: "csv-requsition-status-all"
    maintainHistory:
      required: true
      excludeColumnName:
        - "file_date"
    uniquePattern:
      - "row_unique_number"
    compareBeforeUpdateColumn:
      - "req_date"
      - "dp_date"
      - "remark_date"
      - "material_status"
      - "file_date"
      - "department"
      - "s_no"
      - "items"
      - "unit"
      - "qty"
      - "demand_no"
      - "demand_date"
      - "budget"
      - "req_rate"
      - "req_amount"
      - "allocation"
      - "project_id"
      - "work_id"
      - "estimate_no"
      - "estimate_item_no"
      - "po_number"
      - "dp"
      - "po_rate"
      - "po_amount"
      - "material_received_remark"
      - "bill_paid"
      - "co7_number"
      - "req_remark"
      - "row_unique_number"
      - "project_id_item_no"
      - "estimate_ref_count"
      - "estimate_remark"
      - "indent_status"
      - "category"
      - "sub_category"
      - "make"
    updateColumnName:
      - "req_date"
      - "dp_date"
      - "remark_date"
      - "material_status"
      - "file_date"
      - "department"
      - "s_no"
      - "items"
      - "unit"
      - "qty"
      - "demand_no"
      - "demand_date"
      - "budget"
      - "req_rate"
      - "req_amount"
      - "allocation"
      - "project_id"
      - "work_id"
      - "estimate_no"
      - "estimate_item_no"
      - "po_number"
      - "dp"
      - "po_rate"
      - "po_amount"
      - "material_received_remark"
      - "bill_paid"
      - "co7_number"
      - "req_remark"
      - "row_unique_number"
      - "project_id_item_no"
      - "estimate_ref_count"
      - "estimate_remark"
      - "indent_status"
      - "category"
      - "sub_category"
      - "make"
    columnName:
      - "req_date"
      - "dp_date"
      - "remark_date"
      - "material_status"
      - "file_date"
      - "department"
      - "s_no"
      - "items"
      - "unit"
      - "qty"
      - "demand_no"
      - "demand_date"
      - "budget"
      - "req_rate"
      - "req_amount"
      - "allocation"
      - "project_id"
      - "work_id"
      - "estimate_no"
      - "estimate_item_no"
      - "po_number"
      - "dp"
      - "po_rate"
      - "po_amount"
      - "material_received_remark"
      - "bill_paid"
      - "co7_number"
      - "req_remark"
      - "row_unique_number"
      - "project_id_item_no"
      - "estimate_ref_count"
      - "estimate_remark"
      - "indent_status"
      - "category"
      - "sub_category"
      - "make"
