tableDbConfig:
  - tableConfigId: "get-bill-details"
    tableName: "bill_details"
    orderBy: "id desc"
    defaultFilterMapping:
      "on_roll": ["s&t|signal|telecom|safety|ministrial"]
      "all": [""]
    filterParameter:
      - "bill_unique_number"
    selectColumnName:
      - "bill_date"
      - "material_received_date"
      - "co7_date"
      - "bill_allocation"
      - "bill_type"
      - "s_no"
      - "org_bill_date"
      - "req_no"
      - "description"
      - "org_material_received_date"
      - "qty"
      - "amount"
      - "po_no"
      - "consignee"
      - "agency"
      - "crn_detail"
      - "org_co7_date"
      - "co7_number"
      - "remarks"
      - "project_id"
      - "allocation"
      - "billing_work_id"
      - "bill_allocation_org"
      - "work_id"
      - "bill_unique_number"
      - "irpsm_amount"
      - "detail_escription"
      - "executing_agency"
      - "file_date"
      - "DATE(added_time) as added_date"
    columnName:
      - "bill_date"
      - "material_received_date"
      - "co7_date"
      - "bill_allocation"
      - "bill_type"
      - "s_no"
      - "org_bill_date"
      - "req_no"
      - "description"
      - "org_material_received_date"
      - "qty"
      - "amount"
      - "po_no"
      - "consignee"
      - "agency"
      - "crn_detail"
      - "org_co7_date"
      - "co7_number"
      - "remarks"
      - "project_id"
      - "allocation"
      - "billing_work_id"
      - "bill_allocation_org"
      - "work_id"
      - "bill_unique_number"
      - "irpsm_amount"
      - "detail_escription"
      - "executing_agency"
      - "file_date"
      - "added_date"
  - tableConfigId: "csv-mysql-update-bill-details"
    tableName: "bill_details"
    orderBy: "id desc"
    excelConfigId: "csv-bill-all"
    maintainHistory:
      required: true
      excludeColumnName:
        - "file_date"
    uniquePattern:
      - "bill_unique_number"
    compareBeforeUpdateColumn:
      - "bill_date"
      - "material_received_date"
      - "co7_date"
      - "bill_allocation"
      - "bill_type"
      - "s_no"
      - "org_bill_date"
      - "req_no"
      - "description"
      - "org_material_received_date"
      - "qty"
      - "amount"
      - "po_no"
      - "consignee"
      - "agency"
      - "crn_detail"
      - "org_co7_date"
      - "co7_number"
      - "remarks"
      - "project_id"
      - "allocation"
      - "billing_work_id"
      - "bill_allocation_org"
      - "work_id"
      - "bill_unique_number"
      - "irpsm_amount"
      - "detail_escription"
      - "executing_agency"
      - "file_date"
    updateColumnName:
      - "bill_date"
      - "material_received_date"
      - "co7_date"
      - "bill_allocation"
      - "bill_type"
      - "s_no"
      - "org_bill_date"
      - "req_no"
      - "description"
      - "org_material_received_date"
      - "qty"
      - "amount"
      - "po_no"
      - "consignee"
      - "agency"
      - "crn_detail"
      - "org_co7_date"
      - "co7_number"
      - "remarks"
      - "project_id"
      - "allocation"
      - "billing_work_id"
      - "bill_allocation_org"
      - "work_id"
      - "bill_unique_number"
      - "irpsm_amount"
      - "detail_escription"
      - "executing_agency"
      - "file_date"
    columnName:
      - "bill_date"
      - "material_received_date"
      - "co7_date"
      - "bill_allocation"
      - "bill_type"
      - "s_no"
      - "org_bill_date"
      - "req_no"
      - "description"
      - "org_material_received_date"
      - "qty"
      - "amount"
      - "po_no"
      - "consignee"
      - "agency"
      - "crn_detail"
      - "org_co7_date"
      - "co7_number"
      - "remarks"
      - "project_id"
      - "allocation"
      - "billing_work_id"
      - "bill_allocation_org"
      - "work_id"
      - "bill_unique_number"
      - "irpsm_amount"
      - "detail_escription"
      - "executing_agency"
      - "file_date"
