tableDbConfig:
  - tableConfigId: "get-mysql-staff-details"
    tableName: "staff_rnc"
    orderBy: "id desc"
    defaultFilterMapping:
      "on_roll": ["s&t|signal|telecom|safety|ministrial"]
      "all": [""]
    filterParameter:
      - "department"
    selectColumnName:
      - "file_date"
      - "s_no"
      - "pf_no"
      - "hrms_id"
      - "name"
      - "designation"
      - "department"
      - "gender"
      - "category"
      - "hq"
      - "remarks"
      - "dob"
      - "doa"
      - "dop"
      - "education_qualification"
      - "email"
      - "mobile"
      - "DATE(added_time) as added_time"
      - "DATE(updated_time) as updated_time"
      - "unit"
      - "section"
      - "sub_section"
    columnName:
      - "file_date"
      - "s_no"
      - "pf_no"
      - "hrms_id"
      - "name"
      - "designation"
      - "department"
      - "gender"
      - "category"
      - "hq"
      - "remarks"
      - "dob"
      - "doa"
      - "dop"
      - "education_qualification"
      - "email"
      - "mobile"
      - "added_time"
      - "updated_time"
      - "unit"
      - "section"
      - "sub_section"
  - tableConfigId: "csv-mysql-update-staff-details"
    tableName: "staff_rnc"
    orderBy: "id desc"
    excelConfigId: "csv-user_data-v4-all"
    maintainHistory:
      required: true
      excludeColumnName:
        - "file_date"
    uniquePattern:
      - "hrms_id"
    compareBeforeUpdateColumn:
      - "file_date"
      - "s_no"
      - "pf_no"
      - "hrms_id"
      - "name"
      - "designation"
      - "department"
      - "gender"
      - "category"
      - "hq"
      - "remarks"
      - "dob"
      - "doa"
      - "dop"
      - "education_qualification"
      - "email"
      - "mobile"
      - "unit"
      - "section"
      - "sub_section"
    updateColumnName:
      - "file_date"
      - "s_no"
      - "pf_no"
      - "hrms_id"
      - "name"
      - "designation"
      - "department"
      - "gender"
      - "category"
      - "hq"
      - "remarks"
      - "dob"
      - "doa"
      - "dop"
      - "education_qualification"
      - "email"
      - "mobile"
      - "unit"
      - "section"
      - "sub_section"
    columnName:
      - "file_date"
      - "s_no"
      - "pf_no"
      - "hrms_id"
      - "name"
      - "designation"
      - "department"
      - "gender"
      - "category"
      - "hq"
      - "remarks"
      - "dob"
      - "doa"
      - "dop"
      - "education_qualification"
      - "email"
      - "mobile"
      - "unit"
      - "section"
      - "sub_section"
