tableDbConfig:
  - tableConfigId: "get-sia-data"
    tableName: "sia_data"
    filterParameter:
      - "station"
    columnName:
      - "unit"
      - "sub_unit"
      - "incident_date"
      - "division"
      - "station"
      - "failure_description"
      - "failure_time"
      - "rectification_time"
      - "icms_type"
      - "rb_case"
      - "affected_trains"
      - "affected_trains_goods_count"
      - "train_discription"
      - "remarks"
      - "device"
      - "sub_device"
      - "department"
      - "department_reason"
      - "department_reason_detail"
      - "punctuality_loss_train"
      - "asset_damage"
      - "asset_damage_cost"
      - "device_make"
      - "de_number"
      - "de_date"
      - "failue_memo_no"
      - "disconnection_memo_no"
      - "attended_by"
      - "disconnection_required_at"
      - "disconnection_allowed"
      - "disconnection_allowed_at"
      - "reconnection_given_at"
      - "data_entered_at"
      - "data_entered_by"
      - "data_edited_at"
      - "data_edited_by"
      - "updated_reason"
      - "row_id"
