scanDirConfig:
  - id: "all-path"
    pathIndex:
      - "read-file-path-from-request"
  - id: "test-with-null-path-index"
  - id: "test-1"
    pathIndex:
      - "E:"
      - "E:/"
  - id: "test-2"
    pathIndex:
      - "D:\\workspace"
  - id: "test-3"
    pathIndex:
      - "D:/workspace/ftp-application"
      - "D:/workspace/ftp-application/"
  - id: "test-4"
    csv_mapping_id: "--api-scan-dir-4--"
    device_name: "dev-laptop-4"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/scan-dir-test-folder/single-file-folder"
  - id: "test-5"
    csv_mapping_id: "--api-scan-dir-5--"
    device_name: "dev-laptop-5"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/scan-dir-test-folder/single-file-folder/readme.txt"
  - id: "test-4|test-5"
    csv_mapping_id: "--api-scan-dir--"
    device_name: "dev-laptop"
    pathIndex:
      - "pathIndex parameter will be skipped"
  - id: "D:/workspace/ftp-application"
    pathIndex:
      - "D:/workspace/ftp-application"
  - id: "d-workspace-ftp-application-ftp"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/"
  - id: "workspace-ftp-config-files"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/config-files"
  - id: "workspace-ftp-config-files/"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/config-files/"
  - id: "scan-dir-test-folder"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/scan-dir-test-folder/"
  - id: "workspace-ftp-empty-folder"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/scan-dir-test-folder/empty-folder"
  - id: "workspace-ftp-empty-folder/"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/scan-dir-test-folder/empty-folder/"
  - id: "workspace-ftp-single-file-folder"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/scan-dir-test-folder/single-file-folder"
  - id: "app-env-config-file"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/app_env_config.yml"
      - "D:/workspace/ftp-application/FTP/meta-data/app_env_config_2.yml"
      - "D:/workspace/ftp-application/FTP/meta-data/app_env_config_4.yml"
  - id: "meta-data-dir"
    csv_mapping_id: "--api-scan-dir--"
    device_name: "dev-laptop"
    pathIndex:
      - "D:/workspace/ftp-application/FTP/meta-data/"
  - id: "e-app-data-v2.1-saved-files-shishupal2"
    pathIndex:
      - "E:/app-data-v2.1/project-tracking/saved-files/Shishupal2/"
