tableDbConfig:
  - tableConfigId: "csv-mysql-update-smms_assets_list-ser"
    tableName: "smms_assets_v2"
    excelConfigId: "smms-assets-list-ser"
    maintainHistory:
      required: true
      excludeColumnName:
        - "file_date"
    uniquePattern:
      - "asset_code"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    compareBeforeUpdateColumn:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    updateColumnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "asset_code"
  - tableConfigId: "csv-mysql-update-smms_assets_list-rnc"
    tableName: "smms_assets_v2"
    excelConfigId: "smms-assets-list-rnc"
    maintainHistory:
      required: true
      excludeColumnName:
        - "file_date"
    uniquePattern:
      - "asset_code"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    compareBeforeUpdateColumn:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    updateColumnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "asset_code"
