pageMapping404:
  default:
    fileName: "/app/account/indexv2.html"
  /readme.txt:
    fileName: "/temp.txt"
  /[a-z|0-9]{3}/readme.tx:
    fileName: "/temp.txt"
  /ok/readme.txt:
    fileName: "/temp.txt"
  /bye/readme.txt:
    fileName: "/temp.txt"
