pageMapping404:
  /account:
    fileName: "/app/account/indexv2.html"
  /account/journal:
    fileName: "/app/account/indexv2.html"
  /account/journalbydate:
    fileName: "/app/account/indexv2.html"
  /account/ledger:
    fileName: "/app/account/indexv2.html"
  /account/trialbalance:
    fileName: "/app/account/indexv2.html"
  /account/currentbal:
    fileName: "/app/account/indexv2.html"
  /account/currentbalbydate:
    fileName: "/app/account/indexv2.html"
  /account/currentbalbydatev2:
    fileName: "/app/account/indexv2.html"
  /account/summary:
    fileName: "/app/account/indexv2.html"
  /account/summarybydate:
    fileName: "/app/account/indexv2.html"
  /account/summarybycalander:
    fileName: "/app/account/indexv2.html"
  /account/customisedebit:
    fileName: "/app/account/indexv2.html"
  /account/customisecredit:
    fileName: "/app/account/indexv2.html"
  /account/custompage:
    fileName: "/app/account/indexv2.html"
  /account/profitandloss:
    fileName: "/app/account/indexv2.html"

  /data-path:
    rollAccess: "isLogin"
    fileName: "/data-path-csv-or-json"

