ndTo1dConfig:
  id_1dTo1d:
    sourceExcelId: ["1dTo1dSource"]
    dataStartIndex: 0
    dataDimension: 1
    textColIndex: [0,1,2]

  id_1d_1To1d:
    sourceExcelId: ["1dTo1dSource"]
    dataStartIndex: 0
    dataDimension: 0
    textColIndex: [0,1,2]

  id_1d_2To1d:
    sourceExcelId: ["1dTo1dSource"]
    dataStartIndex: -1
    dataDimension: 1
    textColIndex: [0,1,2]

  id_1d_3To1d:
    sourceExcelId: [""]
    dataStartIndex: -1
    dataDimension: 1
    textColIndex: [0,1,2]

  id_1d_4To1d:
    sourceExcelId: ["invalid"]
    dataStartIndex: -1
    dataDimension: 1
    textColIndex: [0,1,2]

  id_1d_5To1d:
    sourceExcelId: ["1dTo1dSource"]
    dataStartIndex: 0
    dataDimension: 1

  id_2dTo1d:
    sourceExcelId: ["2dTo1dSource"]
    dataStartIndex: 1
    dataDimension: 2
    textColIndex: [0,1,5]
    dataColIndex: [[[2],[0,2]],[[3],[0,3]],[[4],[0,4]]]
    headingField:
      - "SN"
      - "Item"
      - "Remarks"
      - "State"
      - "Value"

  id_2d_1To1d:
    sourceExcelId:
      - "2d_1To1dSource"
    dataStartIndex: 1
    dataDimension: 2
    dataColIndex: [[[0],[0,0]],[[1],[0,1]],[[2],[0,2]],[[3],[0,3]]]
    skipRowCriteria:
      - criteria:
          - col_index: 0
            is_empty: true
  id_3dTo1d:
    sourceExcelId:
      - "3dTo1dSource"
    dataStartIndex: 2
    dataDimension: 3
    textColIndex: [0,1,8]
    dataColIndex:
      - [[2,3],[0,2]]
      - [[4,5],[0,4]]
      - [[6,7],[0,6]]
    skipRowCriteria:
      - dataColIndex: [[0,1]]
        operation: "OR"
        criteria:
          - col_index: 1
            is_empty: true
      - dataColIndex: [[2,2]]
        operation: "AND"
        criteria:
          - col_index: 0
            is_empty: true
          - col_index: 1
            is_empty: true

  id_3d_1To1d:
    sourceExcelId:
      - "3d_1To1dSource"
    dataDimension: 3
    textColIndex: [0,1]
    dataColIndex:
      - [[2],[0,2],[1,2]]
      - [[3],[0,2],[1,3]]
      - [[4],[0,4],[1,4]]
      - [[5],[0,4],[1,5]]
      - [[6],[0,6],[1,6]]
      - [[7],[0,6],[1,7]]
    headingField:
      - "Location"
      - "Row no"
      - "Relay rack"
      - "Relay rack column"
      - "Relay name"
