logging:
  level: INFO
  loggers:
    com.todo: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %c{15} - %msg%n%rEx"
      threshold: ALL
      timeZone: UTC
    - type: file
      threshold: ALL
      timeZone: UTC
      archive: true
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %c{15} - %msg%n%rEx"
      archivedLogFilenamePattern: F:/ftp-app/log/application-%d{yyyy-MM-dd}.log
      currentLogFilename: F:/ftp-app/log/application.log
#      archivedLogFilenamePattern: F:/ftp-app/log/application-%d{yyyy-MM-dd}-%i.log
#      maxFileSize: 1MB
      archivedFileCount: 5 #Number of day archived file to be present


logFilePath: "F:/ftp-app/log/"
fileSaveDir: "D:/workspace/project/ftp-app/saved-files/"
configDataFilePath: "D:/workspace/project/ftp-app/config-files/"

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 8080
    type: http
  rootPath: /*

supportedFileType:
  - pdf
  - txt
  - docx
  - doc
  - xlsx
  - xls
  - pptx
  - ppt
  - mp3
  - 3gp
  - mp4
  - exe
  - jpeg
  - jpg
  - png

defaultFileViewer: "self" #self or all
fileDeleteAccess: "self_admin" #self or admin or self_admin
permanentlyDeleteFile: false #File will saved in trash folder
maxFileSize: 10240001 #i.e. #i.e. 2048000 = 2048 kB = 2MB, 10240001 = 10MB
uploadFileApiVersion: v2 #(v1|v2)

adminUsersName:
  - Admin



# Optional parameter
indexPageReRoute: /login
filenameFormat: "YYYY-MM-dd-HH-mm'-filename'"

# Only for development purpose
createReadmePdf: true
appRestartCommand: "sh app_run.bat" # not required for now
appViewFtlFileName: app_view.ftl
publicDir: "../.."
publicPostDir:
allowedOrigin:
  - http://localhost
  - http://localhost:9000
  - http://localhost:8080
devUsersName:
  - U1
tempConfig:
  username: U1
