logging:
  level: INFO
  loggers:
    com.todo: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %c{15} - %msg%n%rEx"
      threshold: ALL
      timeZone: UTC
    - type: file
      threshold: ALL
      timeZone: UTC
      archive: true
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %c{15} - %msg%n%rEx"
      archivedLogFilenamePattern: F:/ftp-app/log/application-%d{yyyy-MM-dd}.log
      currentLogFilename: F:/ftp-app/log/application.log
#      archivedLogFilenamePattern: F:/ftp-app/log/application-%d{yyyy-MM-dd}-%i.log
#      maxFileSize: 1MB
      archivedFileCount: 5 #Number of day archived file to be present


logFilePath: "F:/ftp-app/log/"
fileSaveDir: "D:/workspace/project/ftp-app/saved-files/"
configDataFilePath: "D:/workspace/project/ftp-app/config-files/"
#configDataFilePath: "D:/workspace/ftp-application/FTP/meta-data/config-files/"

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 8080
    type: http
  rootPath: /*

cookieName: "ftp-cookie-8080"

supportedFileType:
  - pdf
  - txt
  - docx
  - doc
  - xlsx
  - xls
  - pptx
  - ppt
  - mp3
  - 3gp
  - mp4
  - exe
  - jpeg
  - jpg
  - png

defaultFileViewer: "self" #self or all
fileDeleteAccess: "self_admin" #self or admin or self_admin
permanentlyDeleteFile: false #File will saved in trash folder
maxFileSize: 10240001 #i.e. #i.e. 2048000 = 2048 kB = 2MB, 10240001 = 10MB
uploadFileApiVersion: v2 #(v1|v2)
aesEncryptionPassword: "1234"

emailConfig:
  enable: false
  senderEmail: "username@gmail.com"
  senderPassword: "password"

createPasswordEmailConfig:
  createPasswordLink: "http://localhost:8080/create_password"
  createPasswordSubject: "Forgot your password?"
  createPasswordMessage: '<div>
                                <div>Dear <b>%s</b>,</div>
                                <br></br><div>Please find OTP for creating new password: <b>%s</b></div>
                                <br></br><div><a href="%s">Click here</a> for creating new password or, open %s</div>
                                <br></br><div>Please do not reply to this email.</div>
                             </div>'

mysqlEnable: true
# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: mysql
  # the password
  password: mysql
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://localhost:3306/ftpapp?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

backendConfig:
  #  forgotPasswordMessage: "Forgot password request submitted, Please check your email."
  forgotPasswordMessage: "Forgot password request submitted, Please create password."

uiBackendConfig:
  forgotPasswordEnable: false

ftlConfig:
  description: "FTP Application description"
  keywords: "FTP Application, File upload, PDF, JPEG, JPG, PNG"
  author: "FTP Application Author"
  title: "FTP Application"
  gaTrackingId: "UA-177553408-1" # for development
  gaTrackingEnable: true
  displayCreatePasswordLink: false
  uploadFileInstruction: "(Supported type: pdf,jpeg,jpg and png, max size < 10MB)"
  forgotPasswordPageInstruction: "Please contact admin."
#  forgotPasswordPageInstruction: "Please contact admin to get create password otp."
  createPasswordOtpInstruction: "(Receive from admin)"
#  createPasswordOtpInstruction: "(Check your email)"
  headingJson: '[{"tag":"div.center.table.tbody.tr","className":"heading","text":[{"tag":"td","text":{"tag":"img","className":"logo","src":"/assets/static/img/railwayslogo-128.png"}},{"tag":"td","className":"text-center pl-5px","text":[{"tag":"div","text":"Heading Line 1 (config)"},{"tag":"div","text":"Larger Heading Line 2 Row"}]}]}]'

# Optional parameter
indexPageReRoute: /login
filenameFormat: "YYYY-MM-dd-HH-mm'-filename'"
instance: DevComputer
guestEnable: false

# Only for development purpose
createReadmePdf: true
appRestartCommand: "sh app_run.bat" # not required for now
publicDir: "../.."
publicPostDir: "/project"
allowedOrigin:
  - http://localhost
  - http://127.0.0.1:9000
  - http://127.0.0.1:8080
  - http://localhost:9000
  - http://localhost:8080
  - http://localhost:9080
  - chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop

tempConfig1:
  username: U1
