excelConfig:
  excel-data-id-001:
    dateFormat: "dd/MM/yyyy"
    timeFormat: "HH:mm"
    dateTimeFormat: "dd/MM/yyyy HH:mm"
    copyOldData: true
    skipRowIndex:
      - [0, 0]
      - [3, 4]
      - [10, -1]
    appendCellDataIndex:
      - [2, 3]
      - [5, -1]
    fileConfig:
      - source: "D:/workspace/project/nodejs/excel/test/test_data.xlsx"
        destination: "D:/workspace/project/nodejs/excel/test/test_data_4.csv"
        copyDestination: "D:/workspace/project/nodejs/excel/test/test_data_4_copy.csv"
        sheetName: "test-4"
      - source: "D:/workspace/project/nodejs/excel/test/test_data.xlsx"
        destination: "D:/workspace/project/nodejs/excel/test/test_data_2.csv"
        sheetName: "test-2"
  excel-data-id-002:
    fileConfig:
      - source: "D:/workspace/project/nodejs/excel/test/test_data.xlsx"
        destination: "D:/workspace/project/nodejs/excel/test/test_data_2.csv"
        sheetName: "test-2"
  excel-data-id-004:
    fileConfig:
      - source: "D:/workspace/project/nodejs/excel/test/test_data.xlsx"
        destination: "D:/workspace/project/nodejs/excel/test/test_data_4.csv"
        sheetName: "test-4"
  excel-data-id-002-and-004:
    copyOldData: false
    skipEmptyRows: true
    skipRowIndex:
      - [0, 0]
      - [3, 4]
      - [10, -1]
    copyCellDataIndex:
      - 0
      - 1
    appendCellDataIndex:
      - [2, 3]
      - [5, -1]
    cellMapping:
      - defaultCellData: ""
        col_index: 0
        mappingData:
          - col_index: 9
            value: "CNI-MURI"
            range:
              - ILO
              - TRAN
              - SSIA
              - TUL
              - LTMD
              - JHMR
              - GDBR
          - col_index: 9
            value: "MURI-BRKA"
            range:
              - BLNG
              - HRBR
              - GRE
              - BRKP
              - MAEL
              - RMT
          - col_index: 9
            value: "MURI-KSX"
            range:
              - MURI
              - THO
              - JAA
      - defaultCellData: ""
        col_index: 5
        mappingData:
          - col_index: 9
            value: "SL"
            range:
              - ILO
              - TRAN
              - SSIA
              - TUL
              - LTMD
              - JHMR
              - GDBR
              - BLNG
              - HRBR
              - GRE
              - BRKP
              - MAEL
              - RMT
          - col_index: 9
            value: "UP&DN"
            range:
              - MURI
              - THO
              - JAA
      - defaultCellData: "WSL"
        col_index: -1
    fileConfig:
      - source: "D:/workspace/project/nodejs/excel/test/test_data.xlsx"
        destination: "D:/workspace/project/nodejs/excel/test/test_data_4.csv"
        sheetName: "test-4"
      - source: "D:/workspace/project/nodejs/excel/test/test_data.xlsx"
        destination: "D:/workspace/project/nodejs/excel/test/test_data_2.csv"
        sheetName: "test-2"
