fileMappingConfigFilePath: "D:/workspace/ftp-application/FTP/meta-data/config-files/file-mapping-config/file-mapping-config.yml"
scanDirConfigFilePath: "D:/workspace/ftp-application/FTP/meta-data/config-files/scan-dir-config/scan-dir-config.yml"
