pageMapping404:
  /account: "/app/account/indexv2.html"
  /account/: "/app/account/indexv2.html"
  /account/journal: "/app/account/indexv2.html"
  /account/journal/: "/app/account/indexv2.html"
  /account/journalbydate: "/app/account/indexv2.html"
  /account/journalbydate/: "/app/account/indexv2.html"
  /account/ledger: "/app/account/indexv2.html"
  /account/ledger/: "/app/account/indexv2.html"
  /account/trialbalance: "/app/account/indexv2.html"
  /account/trialbalance/: "/app/account/indexv2.html"
  /account/currentbal: "/app/account/indexv2.html"
  /account/currentbal/: "/app/account/indexv2.html"
  /account/currentbalbydate: "/app/account/indexv2.html"
  /account/currentbalbydate/: "/app/account/indexv2.html"
  /account/summary: "/app/account/indexv2.html"
  /account/summary/: "/app/account/indexv2.html"
  /account/summarybydate: "/app/account/indexv2.html"
  /account/summarybydate/: "/app/account/indexv2.html"
  /account/summarybycalander: "/app/account/indexv2.html"
  /account/summarybycalander/: "/app/account/indexv2.html"
  /account/customisedebit: "/app/account/indexv2.html"
  /account/customisedebit/: "/app/account/indexv2.html"
  /account/customisecredit: "/app/account/indexv2.html"
  /account/customisecredit/: "/app/account/indexv2.html"
  /account/custompage: "/app/account/indexv2.html"
  /account/custompage/: "/app/account/indexv2.html"
  /account/profitandloss: "/app/account/indexv2.html"
  /account/profitandloss/: "/app/account/indexv2.html"
