tableDbConfig:
  - tableConfigId: "get-users"
    tableName: "users"
    orderBy: "id desc"
    limit: "100"
    selectColumnName:
      - "id"
      - "username"
      - "change_password_count"
      - "DATE(timestamp) as timestamp"
      - "deleted"
    columnName:
      - "id"
      - "username"
      - "change_password_count"
      - "timestamp"
      - "deleted"
  - tableConfigId: "get-event_data"
    tableName: "event_data"
    orderBy: "id desc"
    limit: "100"
    likeParameter:
      - "event"
    filterParameter:
      - "event"
    columnName:
      - "id"
      - "username"
      - "event"
      - "status"
      - "deleted"
  - tableConfigId: "get-mysql-smms-assets-list"
    tableName: "smms_assets"
    defaultFilterMapping:
      "rnc_division": ["", "Test Ranchi"]
      "asset_unique": ["", "", "Test-DCTMURI00002"]
    filterParameter:
      - "zone"
      - "division"
      - "asset_code"
    allowEmptyFilter: false
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"

  - tableConfigId: "csv-mysql-update-smms_assets_list"
    tableName: "smms_assets"
    excelConfigId: "csv-smms-assets-ser"
    maintainHistory: true
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    compareBeforeUpdateColumn:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    uniquePattern:
      - "asset_code"
    updateColumnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
