tableDbConfig:
  - tableConfigId: "get-users"
    tableName: "users"
    orderBy: "id desc"
    limit: "limit 100"
    selectColumnName:
      - "id"
      - "username"
      - "change_password_count"
      - "DATE(timestamp) as timestamp"
      - "deleted"
    columnName:
      - "id"
      - "username"
      - "change_password_count"
      - "timestamp"
      - "deleted"
  - tableConfigId: "get-event_data"
    tableName: "event_data"
    orderBy: "id desc"
    limit: "limit 100"
    likeParameter:
      - "event"
    filterParameter:
      - "event"
    columnName:
      - "id"
      - "username"
      - "event"
      - "status"
      - "deleted"
  - tableConfigId: "get_smms_assets_list_count"
    tableName: "smms_assets"
    groupBy:
      - "zone"
      - "division"
      - "section_officer"
      - "section"
      - "sub_section"
    selectColumnName:
      - "zone"
      - "division"
      - "section_officer"
      - "section"
      - "sub_section"
      - "COUNT(*) as count"
    columnName:
      - "zone"
      - "division"
      - "section_officer"
      - "section"
      - "sub_section"
      - "count"

  - tableConfigId: "get_smms_assets_list_duplicate"
    tableName: "smms_assets"
    dbType: "oracle"
    defaultDeletedValue: "NO"
    fixedFilterParameter:
      - "asset_code IN (SELECT asset_code FROM smms_assets where deleted='NO' GROUP BY asset_code HAVING COUNT(*) > 1)"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "section_incharge"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "asset_code"
      - "asset_code_v2"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "added_time"
      - "updated_time"

  - tableConfigId: "get_smms_assets_list_count_oracle"
    tableName: "smms_assets"
    dbType: "oracle"
    dbIdentifier: "oracle"
    limit: "FETCH FIRST 500 rows only"
    groupBy:
      - "zone"
      - "division"
      - "section_officer"
      - "section"
      - "sub_section"
    selectColumnName:
      - "zone"
      - "division"
      - "section_officer"
      - "section"
      - "sub_section"
      - "COUNT(*) as count"
    columnName:
      - "zone"
      - "division"
      - "section_officer"
      - "section"
      - "sub_section"
      - "count"
  - tableConfigId: "get-oracle-smms-assets-list"
    tableName: "smms_assets"
    dbType: "oracle"
    defaultDeletedValue: "NO"
    defaultFilterMapping:
      "rnc_division": ["", "Test Ranchi"]
      "asset_unique": ["", "", "Test-DCTMURI00002"]
    filterParameter:
      - "zone"
      - "division"
      - "asset_code"
    allowEmptyFilter: false
    cellMapping:
      - newColumnName: "current_time"
        defaultCellData: "now"
        dateRegex: "yyyy-MM-dd"
        col_index: -1
      - newColumnName: "request_table_config_id"
        col_index: -2
      - newColumnName: "request_default_filter_mapping_id"
        col_index: -3
      - newColumnName: "table_config_id"
        col_index: -4
      - newColumnName: "table_name"
        col_index: -5
      - newColumnName: "db_type"
        col_index: -6
      - newColumnName: "db_identifier"
        col_index: -7
      - newColumnName: "excel_config_id"
        col_index: -8
      - newColumnName: "modified_asset_code"
        defaultCellData: "default modified_asset_code"
        col_index: -1
        mappingData:
          - col_index: 5
            value: "Modified asset code"
            regex: "^Test-DCTMURI00002$"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
  - tableConfigId: "get-mysql-smms-assets-list_oracle"
    tableName: "smms_assets"
    dbType: "oracle"
    defaultFilterMapping:
      "rnc_division": ["", "Test Ranchi"]
      "asset_unique": ["", "", "Test-DCTMURI00002"]
    filterParameter:
      - "zone"
      - "division"
      - "asset_code"
    allowEmptyFilter: true
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"

  - tableConfigId: "csv-mysql-update-smms_assets_list"
    tableName: "smms_assets"
    excelConfigId: "csv-smms-assets-ser"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    maintainHistory:
      required: false
      excludeColumnName:
        - "file_date"
    compareBeforeUpdateColumn:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
    uniquePattern:
      - "asset_code"
    updateColumnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "s_no"
      - "asset_type"
      - "asset_code"
      - "gear_name"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "location"
      - "location_type"
      - "section"
      - "division"
      - "zone"
      - "status"
  - tableConfigId: "csv-mysql-update-smms_assets_list_oracle"
    tableName: "smms_assets"
    excelConfigId: "csv-smms-assets-ser"
    dbType: "oracle"
    defaultDeletedValue: "NO"
    maintainHistory:
      required: true
      excludeColumnName:
        - "file_date"
    uniquePattern:
      - "asset_code_v2"
    columnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "section_incharge"
      - "asset_group1"
      - "asset_group2"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "gear_name"
      - "asset_code"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "asset_code_v2"
    compareBeforeUpdateColumn:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "section_incharge"
      - "asset_group1"
      - "asset_group2"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "gear_name"
      - "asset_code"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "asset_code_v2"
    updateColumnName:
      - "file_date"
      - "sub_section"
      - "section_officer"
      - "section_incharge"
      - "asset_group1"
      - "asset_group2"
      - "s_no"
      - "zone"
      - "division"
      - "section"
      - "location_type"
      - "location"
      - "asset_type"
      - "gear_name"
      - "asset_code"
      - "rfid"
      - "make"
      - "model"
      - "serial_no"
      - "latitude"
      - "longitude"
      - "installation_date"
      - "waranty_expiry_date"
      - "status"
      - "asset_code_v2"
  - tableConfigId: "get_smms_assets_list_view_oracle"
    tableName: "smms_assets"
    dbType: "oracle"
    includeDeleted: false
    joinParam: "INNER JOIN SMMS_ASSET_COUNT ON SMMS_ASSETS.LOCATION=SMMS_ASSET_COUNT.LOCATION and SMMS_ASSETS.ASSET_TYPE=SMMS_ASSET_COUNT.ASSET_TYPE"
    defaultFilterMapping:
      "all": ["NO", "NO"]
    filterParameter:
      - "smms_assets.deleted"
      - "smms_asset_count.deleted"
    groupBy:
      - "SMMS_ASSETS.LOCATION"
      - "SMMS_ASSETS.asset_type"
      - "SMMS_ASSET_COUNT.division_asset_count"
    selectColumnName:
      - "SMMS_ASSETS.LOCATION as location"
      - "SMMS_ASSETS.ASSET_TYPE  as asset_type"
      - "SMMS_ASSET_COUNT.division_asset_count as division_asset_count"
      - "COUNT(*) AS COUNT"
    columnName:
      - "location"
      - "asset_type"
      - "division_asset_count"
      - "count"
