excelFileConfigPath:
  - "D:/workspace/ftp-application/FTP/meta-data/config-files/file-mapping-config/env_config-excel-gs.yml"
  - "D:/workspace/ftp-application/FTP/meta-data/config-files/file-mapping-config/env_config-excel-ms.yml"

googleConfig:
  - fileConfigSourceGoogle: true
    validRequestId: [gs-award,gs-circuit-checking-division,gs-circuit-checking-rb,gs-rbp]
    requiredColIndex: [5,2,3,4]
    fileConfig: ["file-mapping-spreadsheet-id", "file-mapping", "MB-00-ref-data"]

excelConfig:
  - validRequestId:
      - excel-data-id-001
      - excel-data-id-002-and-004
      - csv-test-02
      - csv-test-03
    requiredColIndex: [0,1,2,3]
    fileConfig: ["D:/workspace/ftp-application/FTP/meta-data/test-data/config-data/excel-config.csv", "Excel reading data config path"]

csvConfig:
  - validRequestId:
      - csv-test-01
    requiredColIndex: [ 0,1,2,3]
    fileConfig: [ "D:/workspace/ftp-application/FTP/meta-data/test-data/config-data/csv-config.csv", "CSV reading data config path" ]
